library(shiny)
library(shinythemes)
                                        # Define UI for application that draws a histogram
shinyUI(fluidPage(theme=shinytheme("journal"),
                                        #theme = "bootstrap.min.css",title="Depletion",
                  
                                        #Application title-;
                  ## headerPanel(
                  ##    HTML(
                  ##           '
                  ##          <img src="http://www.cfrn-rcrp.ca/styles/ccfrn_global/images/cfrn_rcrp_logo.png"  width="399" height="102"  alt="Smiley face" > 
                  ##          <img src="http://brand.ubc.ca/files/2012/08/UBCLogo_Black1.png"  width="86" height="102"  alt="Smiley face" align="right" >
                  ##           </div>'
                  ##       )),
                  
                                        # Application title
                  titlePanel("Recruits Per Spawner Prototype Age"),
                  sidebarLayout(
                      sidebarPanel(
                          radioButtons("type", label = h3("Are there Repeat Spawners"),inline=TRUE,
                                       choices = list("Simple" = "S", "Repeat" = "R"),selected = "R"),
                          radioButtons("age", label = h3("Age to plot"),inline=TRUE,
                                       choices = list("1 year old"=1,"2 year old"=2,"3 year old"=3,"4 year old spawner"=4,"4 year old ocean"=5,"5 year old spawner"=6,"5 year old ocean"=7,"6 year old"=8),selected = 4),
                          sliderInput("SF",
                                      "Freshwater Survival:",
                                      sep="",
                                      min = 0,
                                      max =1,
                                      value = .664),
                          sliderInput("SP",
                                      "Passage Survival (DPS*DPE*c):",
                                      sep="",
                                      min = 0,
                                      max =1,
                                      value = .15),
                          sliderInput("SM",
                                      "Marine Survival",
                                      sep="",
                                      min = 0,
                                      max =1,
                                      value = .5975),
                          sliderInput("a",
                                      "Proportion of 4 year olds that spawn:",
                                      sep="",
                                      min = 0,
                                      max =1,
                                      value = .15),
                          sliderInput("b",
                                      "Proportion of 5 year olds that spawn:",
                                      sep="",
                                      min = 0,
                                      max =1,
                                      value = .15),
                          sliderInput("R",
                                      "Proportion of repeat spawners:",
                                      sep="",
                                      min = 0,
                                      max =1,
                                      value = .15),
                          
                          numericInput("F",
                                       "Average Eggs:",
                                       min = 3000,
                                       max =9000,
                                       value = 2416.66),

                          numericInput("N1",
                                       "Initialize 1 year olds:",
                                       min = 0,
                                       max =1000,
                                       value = 2),
                          numericInput("N2",
                                       "Initialize 2 year olds:",
                                       min = 0,
                                       max =1000,
                                       value = 2),
                          numericInput("N3",
                                       "Initialize 3 year olds:",
                                       min = 0,
                                       max =1000,
                                       value = 2),
                          numericInput("N4s",
                                       "Initialize 4 year old spawner:",
                                       min = 0,
                                       max =1000,
                                       value = 2),
                          numericInput("N4o",
                                       "Initialize 4 year old ocean:",
                                       min = 0,
                                       max =1000,
                                       value = 2),
                          numericInput("N5s",
                                       "Initialize 5 year old spawners:",
                                       min = 0,
                                       max =1000,
                                       value = 2),
                          numericInput("N5o",
                                       "Initialize 5 year old  ocean:",
                                       min = 0,
                                       max =1000,
                                       value = 2),
                          numericInput("N6",
                                       "Initialize 6 year olds:",
                                       min = 0,
                                       max =1000,
                                       value = 2),
                          numericInput("years",
                                       "Years:",
                                       min = 0,
                                       max =1000,
                                       value = 5),


                      ),
                      mainPanel(
                          tabsetPanel(type = "tabs",
                                      tabPanel("Full Age", plotOutput("agePlot")),
                                      tabPanel("Full Age Distribution in Last Year", dataTableOutput("age_table")),
                                      tabPanel("Recruit Per Spawner", plotOutput("recruitPlot"))
                                      )))))
